config/routes.rb
Rails.application.routes.draw do
  # get 'relationships/followings'
  # get 'relationships/followers'
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # 管理者用
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
   sessions: "admin/sessions"
  }

  # 顧客用
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  namespace :admin do
    resources :users, only: [:show, :edit, :update, :index, :destroy]
    resources :reports, only: [:index, :show, :update]
    resources :posts, only: [:new, :create, :index, :show, :destroy] do
      resources :comments, only: [:destroy]
    end
  end

  scope module: :public do
    root to: "homes#top"
    resources :users, only: [:show, :edit, :update] do
      resources :reports, only: [:new, :create]
      resource :notifications, only: [:destroy]
      resources :notifications, only: [:index]
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end
    resources :posts, only: [:new, :create, :index, :show, :destroy] do
     resources :likes, only: [:create, :index]
     resource :likes, only: [:destroy]
     resources :greats, only: [:create, :index]
     resource :greats, only: [:destroy]
     resources :amazings, only: [:create, :index]
     resource :amazings, only: [:destroy]
     resources :comments, only: [:create, :destroy]
   end

    get "search" => "searches#search"
    get "friends" => "posts#friends"

    # resources :users, only: [:show, :edit, :update]
  end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  validates :post, { length: { in: 1..200 } }

  has_one_attached :image
  belongs_to :user
  has_many :amazings, dependent: :destroy
  has_many :greats, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
  # has_many :image, dependent: :destroy



  def get_image
    # unless image.attached?
    # file_path = Rails.root.join('app/assets/images/no_image.jpg')
    # image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    # end
    image
  end

  def liked_by?(user)
    likes.exists?(user_id: user.id)
  end

  def greatd_by?(user)
    greats.exists?(user_id: user.id)
  end

  def amazingd_by?(user)
    amazings.exists?(user_id: user.id)
  end

  # サーチ用メソッド
  def self.looks(search, word)
    if search == "perfect_match"
      @post = Post.where("post LIKE?", "#{word}")
    elsif search == "forward_match"
      @post = Post.where("post LIKE?", "#{word}%")
    elsif search == "backward_match"
      @post = Post.where("post LIKE?", "%#{word}")
    elsif search == "partial_match"
      @post = Post.where("post LIKE?", "%#{word}%")
    else
      @post = Post.all
    end
  end

  # いいね通知用メソッド
  def create_notification(current_user, type)
    notification = current_user.active_notifications.new(
      comment_id: nil,
      post_id: id,
      visited_id: user_id,
      action: type
    )
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end




  # コメント通知用メソッド
  def create_notification_comment(current_user, comment_id)
    # byebug
    temp_ids = Comment.where(post_id: id).select(:user_id).where.not("user_id = ? or user_id = ?", current_user.id, user_id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment(current_user, comment_id, temp_id["user_id"])
    end
    save_notification_comment(current_user, comment_id, user_id)
  end

  def save_notification_comment(current_user, comment_id, visited_id) # (通知をした人,通知されたコメント,通知された人)
    notification = current_user.active_notifications.new(
      post_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: "comment"
    )
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  def index
    @posts = Post.includes(:comments).page(params[:page]).per(10).order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_user_path(@post.user)
  end
  
  
  def post_params
    params.require(:post).permit(:post, :image)
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/index.html.erb
<%#= render 'public/xshared/index', resources: @posts %>

app/views/admin/posts/show.html.erb
<div class="card-list-container py-5">
  <div class="card w-50 mx-auto mt-4 shadow-lg">
   <% if @post.get_image.attached? %>
    <%= image_tag @post.get_image %>
   <% end %>
      <div class="card-body">
      <div class="row">
        <div class="col-2">
          <%= link_to admin_user_path(@post.user) do %>
           <%= image_tag @post.user.get_profile_image(60,60), class:"mt-3 rounded-circle"; %>
          <% end %>
        </div>
   <div class="col-10">
     <p class="card-title">
      <%= @post.post %>
     </p>
     <span>
      <i class="fas fa-user"></i> By <%= @post.user.name %>｜
     </span>
     <span>
       <i class="fa fa-calendar"></i> <%= @post.created_at.strftime('%Y/%m/%d') %>｜
     </span>
    <span> <%= link_to "権利者権限で削除",  post_path(@post), class: 'btn btn-warning', method: :delete %>
    </span>



 <hr>
 <div class="comments card-text">
   <h4 class="mt-3"><%= @post.comments.count %>件コメント</h4>
 </div>
 <hr>
    <div class="card-body">
      <div class="row">
        <% @post.comments.each do |post_comment| %>
          <div class="col-2">
              <%= link_to admin_user_path(post_comment.user) do %>
            <%= image_tag post_comment.user.get_profile_image(50,50) %>
            <% end %>
          </div>
          <div class="col-10">
             <p class="card-title">
              <p><%= post_comment.user.name %> | <%= post_comment.created_at.strftime('%Y/%m/%d') %></p>
              <p><b><%= post_comment.comment %></b></p>
               <%= link_to '管理者の権限で削除', admin_post_comment_path(@post.id, post_comment.id),class: "btn btn-warning", method: :delete %>
              <hr>
           </div>
        <% end %>
      </div>
    </div>
    </div>
    </div>
    </div>
    </div>
      </div>
   </div>