config/routes.rb
Rails.application.routes.draw do
  # get 'relationships/followings'
  # get 'relationships/followers'
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # 管理者用
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
   sessions: "admin/sessions"
  }

  # 顧客用
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  namespace :admin do
    resources :users, only: [:show, :edit, :update, :index, :destroy]
    resources :reports, only: [:index, :show, :update]
    resources :posts, only: [:new, :create, :index, :show, :destroy] do
      resources :comments, only: [:destroy]
    end
  end

  scope module: :public do
    root to: "homes#top"
    resources :users, only: [:show, :edit, :update] do
      resources :reports, only: [:new, :create]
      resource :notifications, only: [:destroy]
      resources :notifications, only: [:index]
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end
    resources :posts, only: [:new, :create, :index, :show, :destroy] do
     resources :likes, only: [:create, :index]
     resource :likes, only: [:destroy]
     resources :greats, only: [:create, :index]
     resource :greats, only: [:destroy]
     resources :amazings, only: [:create, :index]
     resource :amazings, only: [:destroy]
     resources :comments, only: [:create, :destroy]
   end

    get "search" => "searches#search"
    get "friends" => "posts#friends"

    # resources :users, only: [:show, :edit, :update]
  end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/report.rb
class Report < ApplicationRecord
  validates :reason, { length: { in: 1..400 } }
  validates :url, { presence: true }


  belongs_to :reporter, class_name: "User"
  belongs_to :reported, class_name: "User"

  enum status: { waiting: 0, keep: 1, finish: 2 }
end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < ApplicationController
  def index
    @reports = Report.all.page(params[:page]).per(10).order(created_at: :desc)  # 全ての通報を取得
  end

  def show
    @report = Report.find(params[:id])  # 特定の通報IDを取得
    @user = @report.reported
    
  end

  def update
    @report = Report.find(params[:id])
    if @report.update(report_params) # ストロングパラメータを通して更新
      flash[:notice] = "対応ステータスを更新しました。"
      redirect_to request.referer
    end
  end

  private
    def report_params
      params.require(:report).permit(:status)
    end
end

app/views/admin/reports/index.html.erb
<div class="col-md-8 offset-md-1">
<h3>通報一覧</h3>

<table class="table">
  <thead>
    <tr>
      <th>通報ID</th>
      <th>会員名</th>
      <th>通報者</th>
      <th>ステータス</th>
    </tr>
  </thead>
  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td>
          <%= link_to report.id, admin_report_path(report) %>
        </td>
        <td>
          <%= report.reported.name %>
        </td>
        <td>
          <%= report.reporter.name %>
        </td>
        <td>
          <%= report.status_i18n %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<div class="row">
 <div class="col-12 d-flex justify-content-center mt-5 ">
   <%= paginate @reports %>
 </div>
</div>

app/views/admin/reports/show.html.erb
<div class="col-md-8 offset-md-1">
<h3 class="page-title">通報詳細</h3>

<table class="table">
    <tbody>
      <tr>
        <td>通報ID</td>
        <td><%= link_to @report.id %></td>
      </tr>
      <tr>
        <td>会員名</td>
        <td><%= link_to "#{@report.reported.name}", admin_user_path(@user.id) %></td>
      </tr>
      <tr>
        <td>理由</td>
        <td><%= @report.reason %></td>
      </tr>
      <tr>
        <td>URL等</td>
        <td><a href=<%= @report.url %>>通報URL</a></td>
      </tr>
      <tr>
        <td>通報者</td>
        <td><%= @report.reporter.name %></td>
      </tr>
      <tr>
        <td>対応ステータス</td>
        <td>
          <%= @report.status_i18n %>
          <%= form_with model:@report, url:admin_report_path(@report), method: :patch, local: true do |f| %>
            <%= f.select :status, Report.statuses.keys.map { |k| [t("enums.report.status.#{k}"), k] } %>
            <%= f.submit '更新' %>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>