config/routes.rb
Rails.application.routes.draw do
  # get 'relationships/followings'
  # get 'relationships/followers'
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # 管理者用
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
   sessions: "admin/sessions"
  }

  # 顧客用
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  namespace :admin do
    resources :users, only: [:show, :edit, :update, :index, :destroy]
    resources :reports, only: [:index, :show, :update]
    resources :posts, only: [:new, :create, :index, :show, :destroy] do
      resources :comments, only: [:destroy]
    end
  end

  scope module: :public do
    root to: "homes#top"
    resources :users, only: [:show, :edit, :update] do
      resources :reports, only: [:new, :create]
      resource :notifications, only: [:destroy]
      resources :notifications, only: [:index]
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end
    resources :posts, only: [:new, :create, :index, :show, :destroy] do
     resources :likes, only: [:create, :index]
     resource :likes, only: [:destroy]
     resources :greats, only: [:create, :index]
     resource :greats, only: [:destroy]
     resources :amazings, only: [:create, :index]
     resource :amazings, only: [:destroy]
     resources :comments, only: [:create, :destroy]
   end

    get "search" => "searches#search"
    get "friends" => "posts#friends"

    # resources :users, only: [:show, :edit, :update]
  end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/xshared/_index.html.erb
<div class="card-list-container py-5">
<% resources.each do |resource| %>
  <div class="card w-50 mx-auto mt-4 shadow-lg">
  <% if resource.get_image.attached? %>
   <%= link_to post_path(resource.id) do %>
     <%= image_tag resource.get_image, class:"card-img-top"; %>
    <% end %>
  <% end %>
    <div class="card-body">
      <div class="row">
        <div class="col-2">
  <!--投稿ユーザー画像-->
         <%= link_to user_path(resource.user.id) do %>
         <%= image_tag resource.user.get_profile_image(60,60), class:"mt-3 rounded-circle"; %>
         <% end %>
        </div>
        <div class="col-10">
          <p class="card-text">
             <%= resource.post %>
          </p>
          <span>
           <i class="fas fa-user"></i> By <%= resource.user.name %>
          </span>
          <div id="like_etc-<%= resource.id %>" >
        <%= render 'public/posts/likes_etc', post: resource %>
       </div>
        </div>
      </div>
    </div>
  </div>
<% end %>


<div class="row">
 <div class="col-12 d-flex justify-content-center mt-5 ">
   <%= paginate resources %>
 </div>
</div>