config/routes.rb
Rails.application.routes.draw do
  # get 'relationships/followings'
  # get 'relationships/followers'
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # 管理者用
  devise_for :admins, skip: [:registrations, :passwords], controllers: {
   sessions: "admin/sessions"
  }

  # 顧客用
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  namespace :admin do
    resources :users, only: [:show, :edit, :update, :index, :destroy]
    resources :reports, only: [:index, :show, :update]
    resources :posts, only: [:new, :create, :index, :show, :destroy] do
      resources :comments, only: [:destroy]
    end
  end

  scope module: :public do
    root to: "homes#top"
    resources :users, only: [:show, :edit, :update] do
      resources :reports, only: [:new, :create]
      resource :notifications, only: [:destroy]
      resources :notifications, only: [:index]
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end
    resources :posts, only: [:new, :create, :index, :show, :destroy] do
     resources :likes, only: [:create, :index]
     resource :likes, only: [:destroy]
     resources :greats, only: [:create, :index]
     resource :greats, only: [:destroy]
     resources :amazings, only: [:create, :index]
     resource :amazings, only: [:destroy]
     resources :comments, only: [:create, :destroy]
   end

    get "search" => "searches#search"
    get "friends" => "posts#friends"

    # resources :users, only: [:show, :edit, :update]
  end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homettete</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">

                  <% if user_signed_in? %>
              <div class="search_form container d-flex justify-content-end mt-2">
                    <%= form_with url: search_path, local: true, method: :get do |f| %>
                    <%= f.text_field :word %>
                    <%= f.select :range, options_for_select([['User'], ['Post']]) %>
                    <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
                    <%= f.submit "検索", class: "btn btn-info" %>
                  <% end %>
                </div>
                <% end %>

      <nav class="navbar navbar-expand-lg navbar-light" style="margin-top: -20px;">
        <div class="container">
          <a class="navbar-brand p-3" href="/"><%= image_tag('logo.png') %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

            <!--ユーザーサインインしていたら-->
        <% if user_signed_in? %>
             <li class="nav-item">
              <%= link_to 'みんなの褒めて', posts_path, class: 'nav-link text-dark' %>
             </li>

             <!--ゲストログインした場合-->
           <% if current_user.name != "guestuser" %>
              <li class="nav-item">
               <%= link_to 'ともだちの褒めて', friends_path, class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to '投稿フォーム', new_post_path, class: 'nav-link text-dark' %>
              </li>
              <li>
              <%= link_to user_notifications_path(current_user.id), class: 'nav-link text-dark' do %>
                <i class="fas fa-bell"></i> 通知
              <% end %>
           <% end %>
              </li>
              <li class="nav-item">
                <%= link_to 'マイページ', user_path(current_user.id), class: 'nav-link text-dark' %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
              </li>
              <!--管理者ログインした場合-->
        <% elsif admin_signed_in? %>
             <li class="nav-item">
              <%= link_to '通報一覧', admin_reports_path, class: 'nav-link text-dark' %>
             </li>
             <li class="nav-item">
              <%= link_to 'ユーザー一覧', admin_users_path, class: 'nav-link text-dark' %>
             </li>
             <li class="navbar-nav ml-auto">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %>
             </li>
        <% else %>
          <!--ユーザーサインインしていない状態-->
            <li class="nav-item">
              <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark' %>
            </li>
        <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
      <div class="col-md-6 mx-auto mt-5">
          <% if flash[:notice] %>
           <p class="text-success"><%= flash[:notice] %></p>
         <% end %>
     </div>
    <%= yield %>

        <span id="back">
          <button>
           <%= image_tag 'arrow.png' %>
          </button>
        </span>


    </main>
    <footer class="bg-dark text-white pt-5 pb-4">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-4">
            <p>褒められたい・褒めたい人の優しいSNS</p>
            <%= image_tag('logo-white.png') %>
          </div>
           <div class="col-md-2">
            <h6 class="text-white mt-2 mb-3">LINEスタンプ発売中♪</h6>
            <p>読み込むorクリック➡</p>
            </div>
            <div class="col-md-4">
            <a class="navbar-brand" href="https://line.me/S/sticker/20800834"><%= image_tag('QR_564489.png') %></a>
            </div>
        </div>
      </div>
    </footer>
  </body>

</html>